name: Test against supported Java versions

on:
  schedule:
    - cron:  '0 4 * * *'
  workflow_dispatch:

permissions: read-all
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '17', '19', '20-ea' ]
    name:  Test against Java ${{ matrix.java }}
    services:
      rabbitmq:
        image: rabbitmq
        ports:
          - 5672:5672

    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@f0bb91606209742fe3ea40199be2f3ef195ecabf # renovate: tag=v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Test
        run: ./gradlew check -i -s -Drabbitmqctl.bin=DOCKER:${{job.services.rabbitmq.id}}